django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
    path('taxes/', include('taxes.urls', namespace='taxes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

taxes/urls.py
from django.urls import path, re_path
from uuid import UUID
from .views import (
    DashboardView, 
    change_status, 
    create_entry, 
    EntryDetailView, 
    get_entry, 
    change_title,
    delete_entry,
    change_description,
    change_body,
    update_receipt,
)
app_name = 'taxes'

urlpatterns = [
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('dashboard/details/<uuid:pk>/', EntryDetailView.as_view(), name='details'),
    path('dashboard/get/<uuid:pk>/', get_entry, name='get_entry'),
    re_path(r'^dashboard/(?P<pk>[\w-]+)/change-status/$', change_status, name='change_status'),
    path('dashboard/create_entry/', create_entry, name='create_entry'),
    path('dashboard/update/<uuid:pk>/title', change_title, name='change_title'),
    path('dashboard/update/<uuid:pk>/description', change_description, name='change_description'),
    path('dashboard/update/<uuid:pk>/body', change_body, name='change_body'),
     path('dashboard/update/<uuid:pk>/receipt', update_receipt, name='update_receipt'),
    path('dashboard/delete/<uuid:pk>/', delete_entry, name='delete_entry'),
]

taxes/models.py
import uuid
from django.db import models
import datetime
from django.contrib.auth import get_user_model

# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class PaymentMethod(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class Entry(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    title = models.CharField(
        max_length=150,
        null=False,
        unique=False,
        verbose_name='entry title',
        help_text='format: required, max characters: 150'
    )
    description = models.CharField(
        max_length=255, 
        null=False,
        unique=False,
        verbose_name='entry description',
        help_text="Enter a brief description of what you bought."
    )
    memo = models.CharField(
        max_length=255, 
        null=True,
        unique=False,
        verbose_name='memo',
        help_text="Not required, memo of the purchase."
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    total_price = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        null=False,
        unique=False,
        default=0.00,
        verbose_name='total price',
        help_text="Required, max digits 10.",
    )
    tax_year = models.IntegerField(
        default=datetime.date.today().year,
        null=False,
        unique=False,
        verbose_name='tax year',
        help_text='required, automatically added'
    )
    purchase_date = models.DateField(
        default=datetime.date.today,
        verbose_name='purchase date',
        null=False,
        unique=False,
        help_text='required, automatically added',
    )
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    receipt_img = models.ImageField(upload_to='entry_images', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

class Item(models.Model):
    name = models.CharField(max_length=255)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    entry = models.ForeignKey(Entry, on_delete=models.PROTECT)

    def __str__(self):
        return self.name
    

taxes/forms.py
from django import forms
from .models import Entry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = [
            'title', 
            'description', 
            'memo',
            'user', 
            'total_price', 
            'tax_year',
            'purchase_date', 
            'status', 
            'category',
            'payment_method',
            'receipt_img',
        ]
        # replace field1, field2, field3 with the actual field names from your Entry model

taxes/views.py
from django.http import HttpResponse, JsonResponse
from django.views.generic import TemplateView, ListView, DetailView
from .models import (
    Entry, 
    Status,
    PaymentMethod,
    Category
)
from .forms import EntryForm
from .helpers import generate_spending_data
from django.shortcuts import get_object_or_404, redirect
from uuid import UUID
import json
from django.contrib.auth import get_user_model
from decimal import Decimal
from datetime import datetime, timedelta
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.decorators import user_passes_test
from accounts.models import CustomUser
from django.utils import timezone
from django.contrib.sessions.models import Session
import matplotlib.pyplot as plt

@user_passes_test(lambda u: u.is_superuser)
def is_superuser(user):
    return user.is_superuser

class DashboardView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Entry
    context_object_name = 'entries'
    template_name = 'taxes/dashboard.html'

    def test_func(self):
        return self.request.user.is_superuser
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        chart_data = generate_spending_data(6)
        chart_labels = []
        chart_values = []
        for label, total in zip(chart_data['labels'], chart_data['totals']):
            chart_labels.append(label)
            chart_values.append(float(total))

        # Retrieve active sessions
        active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
        user_ids = []

        for session in active_sessions:
            data = session.get_decoded()
            user_id = data.get('_auth_user_id', None)
            if user_id:
                user_ids.append(user_id)

        # Get custom user model 
        User = get_user_model()
        # Get online users from User Model 
        online_users = User.objects.filter(id__in=user_ids)

        context['entry_form'] = EntryForm()
        context['payment_methods'] = PaymentMethod.objects.all()
        context['categories'] = Category.objects.all()
        context['statuses'] = Status.objects.all()
        context['users'] = User.objects.all()
        context['online_users'] = online_users
        # Add the chart image path to the context
        context['labels'] = chart_labels
        context['values'] = chart_values
        return context
def change_status(request, pk):
    entry = get_object_or_404(Entry, pk=pk)
    if request.method == 'POST':
        tmp_status = request.POST.get('status')
        status = Status.objects.get(name=tmp_status)
        entry.status = status
        entry.save()
    return redirect('taxes:dashboard')

def change_title(request, pk):
    entry = get_object_or_404(Entry, pk=pk)
    if request.method == 'POST':
        body = json.loads(request.body)
        title = body.get('title')
        if title is None:
             return JsonResponse({'success': False, 'message': 'Title cannot be empty'})
        entry.title = title
        entry.save()
        return JsonResponse({'success': True, 'new_title': entry.title})
    return JsonResponse({'success': False, 'message': 'Invalid request method'})

def change_description(request, pk):
    entry = get_object_or_404(Entry, pk=pk)
    if request.method == 'POST':
        body = json.loads(request.body)
        description = body.get('description')
        if description is None:
             return JsonResponse({'success': False, 'message': 'Description cannot be empty'})
        entry.description = description
        entry.save()
        return JsonResponse({'success': True, 'new_description': entry.description})
    return JsonResponse({'success': False, 'message': 'Invalid request method'})

def update_receipt(request, pk):
    entry = get_object_or_404(Entry, pk=pk)
    if request.method == 'POST':
        receipt_file = request.FILES.get('file', None)
        if receipt_file is None:
            return JsonResponse({'success': False, 'message': 'Image cannot be empty'})
        entry.receipt_img = receipt_file
        entry.save()
        return JsonResponse({'success': True, 'message': 'Success Save'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})


def create_entry(request):
    if request.method == 'POST':
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            entry = form.save()
            return JsonResponse({'success':True})
    
    return JsonResponse({'success':False})

def change_body(request, pk):
    if request.method == 'POST':
        try:
            # Get the entry object
            entry = get_object_or_404(Entry, pk=pk)

            # Update the fields
            entry.category = get_object_or_404(Category, name=request.POST.get('category'))
            entry.tax_year = request.POST.get('tax-year')
            entry.total_price = Decimal(request.POST.get('total-price'))
            entry.purchase_date = datetime.strptime(request.POST.get('purchase-date'), '%Y-%m-%d')
            entry.status = get_object_or_404(Status, name=request.POST.get('status'))
            entry.payment_method = get_object_or_404(PaymentMethod, name=request.POST.get('payment-method'))
            User = get_user_model()
            entry.user = get_object_or_404(User, username=request.POST.get('user'))

            # Save the entry
            entry.save()

            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)}, status=400)
    return HttpResponse('Invalid request method', status=405)

def delete_entry(request, pk):
    if request.method == 'POST':
        entry = get_object_or_404(Entry, pk=pk)
        entry.delete()
        return redirect('taxes:dashboard')
    return HttpResponse('Invalid request method', status=405)

class EntryDetailView(DetailView):
    model = Entry
    template_name = 'taxes/entry_detail.html'

def get_entry(request, pk):
    entry = get_object_or_404(Entry, pk=pk)
    data = {
        "title": entry.title,
        "description": entry.description,
        "memo": entry.memo,
        "user": entry.user.username,
        "total_price": str(entry.total_price),
        "tax_year": str(entry.tax_year),
        "purchase_date": str(entry.purchase_date),
        "status": entry.status.name,
        "category": entry.category.name,
        "payment_method": entry.payment_method.name,
        "created_at": str(entry.created_at),
        "updated_at": str(entry.updated_at),
        "img": str(entry.receipt_img),
    }
    json_data = json.dumps(data)
    return HttpResponse(json_data, content_type="application/json")

templates/taxes/add_entry.html
<script>
    // get references to the button, modal, and form elements
    const addItemBtn = document.getElementById('add-item-btn');
    const modal = document.getElementById('add-entry-modal');
    const closeModalBtn = document.getElementById('close-modal-btn');
    const form = document.getElementById('entry-form');

    // add a click event listener to the button to show the modal
    addItemBtn.addEventListener('click', function() {
        console.log('Add Item Clicked')
        modal.classList.remove('hidden');
    });

    closeModalBtn.addEventListener('click', function() {
        console.log('Hide Modal Clicked')
        modal.classList.add('hidden');
    });

    
    function updateTable(data) {
        // Get the table body element
        var tableBody = document.getElementById('table-body');
      
        // Clear the existing rows
        tableBody.innerHTML = '';
        console.log(data.length)
        // Loop through the data and create a new row for each item
        for (var i = 0; i < data.length; i++) {
          var newRow = document.createElement('tr');
          console.log(data[i])
          var titleCell = document.createElement('td');
          titleCell.innerText = data[i].title;
          newRow.appendChild(titleCell);
      
          tableBody.appendChild(newRow);
        }
    }


    document.getElementById('add-entry-form').addEventListener('submit', function(event) {
        // prevent default form submission behavior
        event.preventDefault();

        // serialize form data
        var formData = new FormData(this);
        console.log(formData)

        // send AJAX request
        $.ajax({
            url: '{% url 'taxes:create_entry'%}',
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function(data) {
                // check to see if object was created successfully 
                if (data.success) {
                    // append new object to table
                    console.log(data.title)
                    updateTable(data);

                    // hide modal 
                    modal.classList.add('hidden');
                }
                else {
                    alert('Error in creating object!');
                }

            },
            error: function() {
                alert('Error creating object!');
            }
        });

    });



    // add a submit event listener to the form to handle the form submission
    $(function() {
        $('#add-item-btn').click(function() {
            $('#modal').removeClass('hidden');
        });
        $('#new-entry-form').submit(function(e) {
            e.preventDefault();
            $.post('{% url "admin:login" %}', $(this).serialize(), function(response) {
                if (response.success) {
                window.location.reload();
                }
            });
        });
    });

</script>

templates/taxes/entry_detail.html
{% extends "_base.html" %}

{% block title%}About Page{% endblock title%}

{% block content %}
    <h1>About Page</h1>
{% endblock %}

templates/taxes/spending_chart.html
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
        labels: {{ labels|safe }},
        datasets: [{
            label: 'Recent Spending',
            data: {{ values|safe }},
            backgroundColor: 'rgba(255, 99, 132, 0.2)',
            borderColor: 'rgba(255, 99, 132, 1)',
            borderWidth: 1
        }]
        },
        options: {
        scales: {
            yAxes: [{
            ticks: {
                beginAtZero: true
            }
            }]
        }
        }
    });
</script>