django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
    path('taxes/', include('taxes.urls', namespace='taxes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('',HomePageView.as_view(),name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

taxes/urls.py
from django.urls import path, re_path
from uuid import UUID
from .views import (
    DashboardView, 
    change_status, 
    create_entry, 
    EntryDetailView, 
    get_entry, 
    change_title,
    delete_entry,
    change_description,
    change_body,
    update_receipt,
)
app_name = 'taxes'

urlpatterns = [
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('dashboard/details/<uuid:pk>/', EntryDetailView.as_view(), name='details'),
    path('dashboard/get/<uuid:pk>/', get_entry, name='get_entry'),
    re_path(r'^dashboard/(?P<pk>[\w-]+)/change-status/$', change_status, name='change_status'),
    path('dashboard/create_entry/', create_entry, name='create_entry'),
    path('dashboard/update/<uuid:pk>/title', change_title, name='change_title'),
    path('dashboard/update/<uuid:pk>/description', change_description, name='change_description'),
    path('dashboard/update/<uuid:pk>/body', change_body, name='change_body'),
     path('dashboard/update/<uuid:pk>/receipt', update_receipt, name='update_receipt'),
    path('dashboard/delete/<uuid:pk>/', delete_entry, name='delete_entry'),
]

templates/_base.html
<!-- templates/_base.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.17/dist/tailwind.min.css">
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/dropzone.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.2/min/dropzone.min.js"></script>
    
</head>

<body>
    <div class="mx-auto p-5">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/about.html
{% extends "_base.html" %}

{% block title%}About Page{% endblock title%}

{% block content %}
    <h1>About Page</h1>
{% endblock %}

templates/home.html
{% extends "_base.html" %}

{% block title%}{% endblock title%}

{% block content %}
    <section class="hero">
        <div class="flex gap-1 flex-row">
            <div class="rounded-xl overflow-hidden p-5 md:p-10 flex h-full w-2/3 items-center bg-brand-green font-bold leading-none sm:w-auto md:justify-start md:px-10 md:text-lg md:leading-none">
                <h3 class="text-white">NaviGrounds</h3>
            </div>
            <div class="rounded-xl overflow-hidden p-5 md:p-10 hidden flex-grow bg-brand-green sm:block"></div>
            <button class="inline-flex items-center gap-2 xl:gap-5 group rounded-full text-white py-.5 hover:bg-black hover:text-white antialiased transition-colors text-xl w-1/3 justify-center bg-secondary-green px-10 sm:w-auto">Menu</button>
        </div>
        <div class="flex grow flex-col gap-1 md:flex-row my-1">
            <div class="rounded-xl overflow-hidden col-span-2 p-5 md:col-span-1 md:w-1/2 md:p-10">
                <div class="flex flex-col h-full gap-10 md:gap-10">
                    <h1 class=" font-brand text-5xl text-gray-900 font-bold leading-none sm:text-5xl sm:leading-none md:text-[4.8vw]">
                        A place for all things Navi. Upload recipts for taxes & of course I will be making another <span class="text-green-500">spam James app!<span></span>
                    </h1>
                    <p class="text-gray-900 md:text-2xl text-2xl md:leading-tight antialiased md:mt-auto">
                        There is so much to do here, if you are here from my resume please look at the bottom of the pdf for the login credentials!
                    </p>
                    {% if user.is_authenticated %}
                        <div class="flex">
                            <a href="{% url 'admin:login' %}" class="flex-1 bg-brand-green hover:bg-white hover:text-black text-white font-bold py-2 px-4 rounded-full text-center mx-2 shadow-outline">Hello {{user.username}}!</a>
                            <a href="{% url 'account_logout' %}" class="flex-1 bg-brand-green hover:bg-white hover:text-black text-white font-bold py-2 px-4 rounded-full text-center mx-2 shadow-outline">Logout!</a>
                        </div> 
                    {% else %}
                        <a href="{% url 'account_login' %}" class="rounded-xl bg-brand-green hover:bg-black hover:text-white text-white font-bold py-4 px-4 rounded w-full text-center">Sign into NaviGrounds!</a>
                    {% endif %}
                </div>
            </div>
            <div class="hero-flex">
                {% load static %}
                <a class="border border-gray-300 bg-white hover:bg-green-900 hover:text-white rounded-xl hero-card" href={% url 'taxes:dashboard'%}>
                    <div class="hero-card-img-container">
                        <img class="hero-card-img" src="{% static '/images/tax_app_img.svg' %}">
                        <div class="hero-card-divider"></div>
                    </div>
                    <div class="hero-card-text">
                        <h3 class="hero-card-title font-brand">Tax App!</h3>
                        <p class="hero-card-description">Upload & Track Contributions!</p>
                    </div>
                </a>
                <a class="border border-gray-300 bg-white hover:bg-green-900 hover:text-white rounded-xl hero-card" href={% url 'taxes:dashboard'%}>
                    <div class="hero-card-img-container">
                        <img class="hero-card-img" src="{% static '/images/trade_app_img.svg' %}">
                        <div class="hero-card-divider"></div>
                    </div>
                    <div class="hero-card-text">
                        <h3 class="hero-card-title font-brand">Trade bot</h3>
                        <p class="hero-card-description">Create your watchlist and then let the AI make you money.</p>
                    </div>
                </a>
                <a class="border border-gray-300 bg-white hover:bg-green-900 hover:text-white rounded-xl hero-card" href={% url 'taxes:dashboard'%}>
                    <div class="hero-card-img-container">
                        <img class="hero-card-img" src="{% static '/images/reciperun_img.svg' %}">
                        <div class="hero-card-divider"></div>
                    </div>
                    <div class="hero-card-text">
                        <h3 class="hero-card-title font-brand">Shop Runner</h3>
                        <p class="hero-card-description">Automatically fill your cart and checkout!</p>
                    </div>
                </a>
                <a class="border border-gray-300 bg-white hover:bg-green-900 hover:text-white rounded-xl hero-card" href={% url 'taxes:dashboard'%}>
                    <div class="hero-card-img-container">
                        <img class="hero-card-img" src="{% static '/images/spam_app_img.svg' %}">
                        <div class="hero-card-divider"></div>
                    </div>
                    <div class="hero-card-text">
                        <h3 class="hero-card-title font-brand">Spam James</h3>
                        <p class="hero-card-description">Text James at any moment, until he blocks this :(</p>
                    </div>
                </a>
                <a class="border border-gray-300 bg-white hover:bg-green-900 hover:text-white rounded-xl hero-card" href={% url 'taxes:dashboard'%}>
                    <div class="hero-card-img-container">
                        <img class="hero-card-img" src="{% static '/images/splice_app_img.svg' %}">
                        <div class="hero-card-divider"></div>
                    </div>
                    <div class="hero-card-text">
                        <h3 class="hero-card-title font-brand">FiberLogic</h3>
                        <p class="hero-card-description">Best record keeping for all splicing needs.</p>
                    </div>
                </a>
            </div>
        </div>
        <div class="rounded-xl block h-40 bg-brand-green relative">
          <marquee class="absolute top-0 left-1/2 transform -translate-x-1/2 h-full w-full py-8" behavior="scroll" direction="left" scrollamount="20">
            <span class="text-8xl leading-40 text-bold font-brand text-white text-center">
              Scroll for more awesome stuff!!!! Scroll for more awesome stuff!!!!
            </span>
            <span class="text-8xl leading-40 text-bold font-brand text-white text-center">
              Scroll for more awesome stuff!!!! Scroll for more awesome stuff!!!!
            </span>
          </marquee>
        </div>
        
    </section>
{% endblock content %}